In [ ]:
# H1 TITLE
## H2 TITLE

In [1]:
print("Buy the dip ?")

Buy the dip ?


In [10]:
import numpy as np

my_int = 21
my_float = 1.21
my_string = "Hello"
my_dict = {"key": "value"}
my_list = [1, 2, 3]
my_tuple = (4, 5, 6)
my_set = {7, 8, 9}
my_bool = True

your_np_array = np.array([
    my_int,
    my_float,
    my_string,
    my_dict,
    my_list,
    my_tuple,
    my_set,
    my_bool
], dtype = object)

In [11]:
for i in your_np_array:
    print(type(i))

<class 'int'>
<class 'float'>
<class 'str'>
<class 'dict'>
<class 'list'>
<class 'tuple'>
<class 'set'>
<class 'bool'>


In [12]:
zero_array = np.zeros(300)
reshaped_array = zero_array.reshape(3, 100)
print(reshaped_array)
print("Shape of reshaped array:", reshaped_array.shape)


[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0.]]
Shape of reshaped array: (3, 100)


In [14]:
array_q1 = np.arange(1, 101)
print(array_q1)
odd_numbers = array_q1[array_q1 % 2 != 0]
print(odd_numbers)
even_numbers_reversed = array_q1[array_q1 % 2 == 0][::-1]
print(even_numbers_reversed)
array_q1[1::3] = 0
print(array_q1)



[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]
[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95
 97 99]
[100  98  96  94  92  90  88  86  84  82  80  78  76  74  72  70  68  66
  64  62  60  58  56  54  52  50  48  46  44  42  40  38  36  34  32  30
  28  26  24  22  20  18  16  14  12  10   8   6   4   2]
[  1   0   3   4   0   6   7   0   9  10   0  12  13   0  15  16   0  18
  19   0  21  22   0  24  25   0  27  28   0  30  31   0  33  34   0  36
  37   0  39  40   0  42  43   0  45  46   0  48  49   0  51  52   0  54
  55   0  57  58

In [15]:

np.random.seed(888)
normal_dist_array = np.random.normal(size=100)
random_integers_2d = np.random.randint(1, 11, size=(8, 8))
random_integers_3d = np.random.randint(1, 18, size=(4, 2, 5))

print("1D Array with Normal Distribution:\n", normal_dist_array)
print("\n2D Array (8x8) with Random Integers from 1 to 10:\n", random_integers_2d)
print("\n3D Array (4x2x5) with Random Integers from 1 to 17:\n", random_integers_3d)


1D Array with Normal Distribution:
 [-1.76200874e-01  1.88876361e-01  8.26747180e-01 -3.24473146e-02
 -6.52499418e-01 -1.05339382e-01  2.17776116e-01  5.87281504e-01
  1.00237892e-01 -1.09994668e+00 -2.55305389e-01  4.05304381e-01
  1.62663953e-01  1.04163462e+00  2.24324184e-01  6.99304449e-01
 -8.65543512e-01 -1.39346831e+00 -2.36687913e-01 -7.57041911e-01
  1.31429195e+00 -9.77385899e-01 -3.59032576e-01  1.16141585e-01
 -3.51081138e-01 -4.39838344e-01 -4.90995473e-02 -4.31596770e-01
 -1.08875099e+00 -2.31088106e+00 -1.86236420e+00  2.34708674e-01
 -8.95585921e-01 -5.40834525e-01 -4.02399061e-01  2.31458561e-02
  1.77688506e-01 -5.73309272e-01 -3.38392138e-01 -2.64422114e-03
  1.44930339e+00  1.36605641e+00  2.69187461e+00  6.76065035e-01
 -1.06098418e+00  1.31845313e-01  1.71934297e-01  8.88062794e-02
  1.03963016e+00 -1.37846942e-01 -3.69232844e-01  3.19587912e+00
  1.11457451e+00 -2.59516296e-01  1.48370897e+00 -1.57049065e+00
  9.78899330e-01  1.76070681e+00  3.53121953e-01 -3.08

In [16]:

array_1_to_50 = np.arange(1, 51)
array_51_to_100 = np.arange(51, 101)
concatenated_array = np.concatenate((array_1_to_50, array_51_to_100))
reshaped_array = concatenated_array.reshape(10, 10)

print("Array from 1 to 50:\n", array_1_to_50)
print("\nArray from 51 to 100:\n", array_51_to_100)
print("\nConcatenated Array:\n", concatenated_array)
print("\nReshaped Array (10x10):\n", reshaped_array)


Array from 1 to 50:
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50]

Array from 51 to 100:
 [ 51  52  53  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68
  69  70  71  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86
  87  88  89  90  91  92  93  94  95  96  97  98  99 100]

Concatenated Array:
 [  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]

Reshaped Array (10x10):
 [[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33

In [17]:
array_9x9 = np.ones((9, 9), dtype=np.int8)
array_9x9[1:8, 1:8] = 0
array_9x9[2:7:2, 2:7:2] = 1
array_9x9[3:6:2, 3:6:2] = 1
array_1 = np.array([1, 2, 3, 4, 5], dtype=np.int8)
array_2 = np.array([1, 2, 3], dtype=np.int8)
print("arrray 9x9:")
print(array_9x9)
array_1 = np.array([1, 2, 3, 4, 5], dtype=np.int8)
array_2 = np.array([1, 2, 3], dtype=np.int8)

multiplication_table = np.outer(array_1, array_2)
print("\nmultiplication table:")
print(multiplication_table)

arrray 9x9:
[[1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 1]
 [1 0 1 0 1 0 1 0 1]
 [1 0 0 1 0 1 0 0 1]
 [1 0 1 0 1 0 1 0 1]
 [1 0 0 1 0 1 0 0 1]
 [1 0 1 0 1 0 1 0 1]
 [1 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1]]

multiplication table:
[[ 1  2  3]
 [ 2  4  6]
 [ 3  6  9]
 [ 4  8 12]
 [ 5 10 15]]


In [18]:
generator = np.random.default_rng(123)
grades = np.round(generator.uniform(low=0.0, high=10.0, size=(10, 2)))
grades[[1, 2, 5, 7], [0, 0, 0, 0]] = np.nan

third_column = np.where(~np.isnan(grades[:, 0]), grades[:, 0], grades[:, 1])
grades = np.hstack((grades, third_column.reshape(-1, 1)))

print(grades)


[[ 7.  1.  7.]
 [nan  2.  2.]
 [nan  8.  8.]
 [ 9.  3.  9.]
 [ 8.  9.  8.]
 [nan  2.  2.]
 [ 8.  2.  8.]
 [nan  6.  6.]
 [ 9.  2.  9.]
 [ 8.  5.  8.]]


In [41]:
file_path = '/home/kooduser/winequality-red.txt'
data = np.genfromtxt(file_path, delimiter=';', skip_header=1, dtype=np.float32)

print(data[:,:]) 
print(f'size of array: {data.nbytes} bait') 
rows = data[[1, 6, 11], :]

cleaned_rows = rows[~np.isnan(rows).any(axis=1)]
print(cleaned_rows)

alcohol_column = data[:, -2]
has_high_alcohol = np.any(alcohol_column > 20)
print(has_high_alcohol)  # True or False

average_alcohol = np.nanmean(alcohol_column)
print(average_alcohol)

pH_column = data[:, -4]  
pH_cleaned = pH_column[~np.isnan(pH_column)]

pH_stats = {
    'min': np.min(pH_cleaned),
    'max': np.max(pH_cleaned),
    '25th_percentile': np.percentile(pH_cleaned, 25),
    '50th_percentile': np.percentile(pH_cleaned, 50),
    '75th_percentile': np.percentile(pH_cleaned, 75),
    'mean': np.mean(pH_cleaned),
}
print(pH_stats)

sulphates_column = data[:, -3] 

percentile_20 = np.percentile(sulphates_column, 20)

low_sulphates_mask = sulphates_column < percentile_20

low_sulphates_quality = data[low_sulphates_mask, -1] 
average_quality = np.mean(low_sulphates_quality)
print(average_quality)

quality_column = data[:, -1]  

max_quality = np.max(quality_column)
min_quality = np.min(quality_column)

best_quality_mask = quality_column == max_quality
worst_quality_mask = quality_column == min_quality

mean_best_quality = np.mean(data[best_quality_mask], axis=0)
mean_worst_quality = np.mean(data[worst_quality_mask], axis=0)

print('Average values for the best wines:', mean_best_quality)
print('Average values for the worst wines:', mean_worst_quality)



[[ 7.4    0.7    0.    ...  0.56   9.4    5.   ]
 [ 7.8    0.88   0.    ...  0.68   9.8    5.   ]
 [ 7.8    0.76   0.04  ...  0.65   9.8    5.   ]
 ...
 [ 6.3    0.51   0.13  ...  0.75  11.     6.   ]
 [ 5.9    0.645  0.12  ...  0.71  10.2    5.   ]
 [ 6.     0.31   0.47  ...  0.66  11.     6.   ]]
size of array: 76752 bait
[[7.800e+00 8.800e-01 0.000e+00 2.600e+00 9.800e-02 2.500e+01 6.700e+01
  9.968e-01 3.200e+00 6.800e-01 9.800e+00 5.000e+00]
 [7.900e+00 6.000e-01 6.000e-02 1.600e+00 6.900e-02 1.500e+01 5.900e+01
  9.964e-01 3.300e+00 4.600e-01 9.400e+00 5.000e+00]
 [7.500e+00 5.000e-01 3.600e-01 6.100e+00 7.100e-02 1.700e+01 1.020e+02
  9.978e-01 3.350e+00 8.000e-01 1.050e+01 5.000e+00]]
False
10.422984
{'min': np.float32(2.74), 'max': np.float32(4.01), '25th_percentile': np.float32(3.21), '50th_percentile': np.float32(3.31), '75th_percentile': np.float32(3.4), 'mean': np.float32(3.3111134)}
5.1854305
Average values for the best wines: [ 8.566666    0.4233333   0.39111114  2.57777

In [44]:
import numpy as np
import itertools

raw_data = """0,-2.30,-4.59,-4.83,3.13,4.13,1.07,2.29,0.44,4.35
2.30,0,3.57,-4.66,2.30,-3.24,3.63,0.41,-2.00,-0.77
4.59,-3.57,0,1.47,1.15,-1.16,4.97,4.81,1.86,1.50
4.83,4.66,-1.47,0,0.25,-1.90,-0.14,3.89,4.34,-1.42
-3.13,-2.30,-1.15,-0.25,0,3.90,-2.73,1.23,-4.16,3.33
-4.13,3.24,1.16,1.90,-3.90,0,-0.50,2.96,-2.69,-4.48
-1.07,-3.63,-4.97,0.14,2.73,0.50,0,4.42,-1.35,-3.95
-2.29,-0.41,-4.81,-3.89,-1.23,-2.96,-4.42,0,4.49,-0.40
-0.44,2.00,-1.86,-4.34,4.16,2.69,1.35,-4.49,0,2.29
-4.35,0.77,-1.50,1.42,-3.33,4.48,3.95,0.40,-2.29,0"""

forecasts = np.array([line.split(',') for line in raw_data.split('\n')], dtype=float)

teams = list(range(10))
possible_arrangements = list(itertools.permutations(teams, 10))

min_score = float('inf')
best_arrangement = None

for arr in possible_arrangements:
    pairs = [(arr[i], arr[i+1]) for i in range(0, 10, 2)]
    score = sum(forecasts[t1, t2]**2 for t1, t2 in pairs)
    
    if score < min_score:
        min_score = score
        best_arrangement = arr

# Convert numerical results to the required format
result = np.array([
    [f"m{i+1}_t1" for i in range(5)],
    [f"m{i+1}_t2" for i in range(5)]
])

print(result)

[['m1_t1' 'm2_t1' 'm3_t1' 'm4_t1' 'm5_t1']
 ['m1_t2' 'm2_t2' 'm3_t2' 'm4_t2' 'm5_t2']]
